---

# This config file contains multi agent collaboration 
# parameters that are configurable and can be used across the 
# working repository. This includes the models used for sub agents, 
# inference parameters, etc.
multi-agent-collaboration-info:
  # Represents the sub agents and their respective information
  fundamental_analyst_sub_agent:
    model:
  technical_analyst_sub_agent:
    model:
  marketing_analyst_sub_agent:
    model:
  